app:
  port: 8888

kafka:
  addr:
    - "localhost:29092"
  writeTimeout: 2
  readTimeout: 2
  retryCount: 3
  commitInterval: 1
  startOffset: -2 #从最开始开始读

mysql:
  tcp: "127.0.0.1:3306"
  user: "user"
  password: "password"
  database: "osdbms"


redis:
  tcp: "127.0.0.1:6379"

