// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLocation = "location"

// Location mapped from table <location>
type Location struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ShipID    int32     `gorm:"column:ship_id;not null" json:"ship_id"`
	Longitude float64   `gorm:"column:longitude;not null" json:"longitude"`
	Latitude  float64   `gorm:"column:latitude;not null" json:"latitude"`
	Timestamp time.Time `gorm:"column:timestamp;not null" json:"timestamp"`
	CreatedAt time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Extra     string    `gorm:"column:extra" json:"extra"`
}

// TableName Location's table name
func (*Location) TableName() string {
	return TableNameLocation
}
