// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOriginalMessageStationTwo = "original_message_station_two"

// OriginalMessageStationTwo mapped from table <original_message_station_two>
type OriginalMessageStationTwo struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OriginatorNumber  string    `gorm:"column:originator_number;not null" json:"originator_number"`
	DestinationNumber string    `gorm:"column:destination_number;not null" json:"destination_number"`
	MessageType       bool      `gorm:"column:message_type;not null" json:"message_type"`
	Timestamp         time.Time `gorm:"column:timestamp;not null" json:"timestamp"`
	Longitude         float64   `gorm:"column:longitude;not null" json:"longitude"`
	Latitude          float64   `gorm:"column:latitude;not null" json:"latitude"`
	MessageContent    string    `gorm:"column:message_content" json:"message_content"`
	CreatedAt         time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Extra             string    `gorm:"column:extra" json:"extra"`
}

// TableName OriginalMessageStationTwo's table name
func (*OriginalMessageStationTwo) TableName() string {
	return TableNameOriginalMessageStationTwo
}
