// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePermission = "permission"

// Permission mapped from table <permission>
type Permission struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Identification int32     `gorm:"column:identification;not null" json:"identification"`
	CreatedAt      time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Extra          string    `gorm:"column:extra" json:"extra"`
}

// TableName Permission's table name
func (*Permission) TableName() string {
	return TableNamePermission
}
