// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameShip2mi = "ship2mis"

// Ship2mi mapped from table <ship2mis>
type Ship2mi struct {
	ID                int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	OriginatorShipID  int32     `gorm:"column:originator_ship_id;not null" json:"originator_ship_id"`
	DestinationShipID int32     `gorm:"column:destination_ship_id;not null" json:"destination_ship_id"`
	Timestamp         time.Time `gorm:"column:timestamp;not null" json:"timestamp"`
	MessageContent    string    `gorm:"column:message_content;not null" json:"message_content"`
	CreatedAt         time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Extra             string    `gorm:"column:extra" json:"extra"`
}

// TableName Ship2mi's table name
func (*Ship2mi) TableName() string {
	return TableNameShip2mi
}
