// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username     string    `gorm:"column:username;not null" json:"username"`
	Password     string    `gorm:"column:password;not null" json:"password"`
	PermissionID int32     `gorm:"column:permission_id;not null" json:"permission_id"`
	CreatedAt    time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Extra        string    `gorm:"column:extra" json:"extra"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
